set-option global tabstop 3		# Width of a tab
set-option global indentwidth 3	# Indent with 3 spaces
set-option global scrolloff 99,3	# Center cursor

# Colorscheme
colorscheme lena

# Change selection color based on mode
set-face global PrimarySelection white,rgb:5C8CDC+F
set-face global SecondarySelection black,rgb:86A7E0+F
set-face global PrimaryCursor white,rgb:8C56EB+F
set-face global SecondaryCursor black,rgb:AE8DEB+F
set-face global PrimaryCursorEol black,rgb:DB4979
set-face global SecondaryCursorEol black,rgb:E084A3

hook global ModeChange ".*:insert" %{
	set-face window PrimarySelection white,rgb:5C8CDC+F
	set-face window SecondarySelection black,rgb:86A7E0+F
	set-face window PrimaryCursor white,rgb:4CD0A0+F
	set-face window SecondaryCursor black,rgb:94DCC2+F
	set-face window PrimaryCursorEol black,rgb:677a8f
	set-face window SecondaryCursorEol black,rgb:4F6074
}

hook global ModeChange ".*:normal" %{
	unset-face window PrimarySelection
	unset-face window SecondarySelection
	unset-face window PrimaryCursor
	unset-face window SecondaryCursor
	unset-face window PrimaryCursorEol
	unset-face window SecondaryCursorEol
}

# Line numbers
add-highlighter global/ number-lines -relative -separator '  '

#add-highlighter global/ regex \h+$ 0:Error	# Highlight trailing whitespace

# Colemak bindings
map global normal n h
map global normal N H
map global normal e j
map global normal E J
map global normal i k
map global normal I K
map global normal o l
map global normal O L
map global normal h i
map global normal H I
map global normal j e
map global normal J E
map global normal k n
map global normal K N
map global normal l o
map global normal L O

map global goto n h
map global goto e j
map global goto i k
map global goto o l


# Set space to leader key
map global normal <space> ,
map global normal , <space>

# Global clipboard mappings
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i -b<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"


# Shortcuts to exit
map global user w -docstring 'write' ': w<ret>'
map global user q -docstring 'quit' ': q<ret>'
map global user z -docstring 'write and quit' ': wq<ret>'

# Cycle autocompletions with Tab
hook global InsertCompletionShow .* %{
   try %{
      exec -draft 'h<a-K>\h<ret>'
      map window insert <s-tab> <c-p>
      map window insert <tab> <c-n>
   }
}

hook global InsertCompletionHide .* %{
   unmap window insert <tab> <c-n>
   unmap window insert <s-tab> <c-p>
}
