#!/bin/sh

col -b -x | kak -e "set buffer filetype man; map global normal q ':quit!<ret>'; remove-highlighter window/number-lines_-relative_-separator_  "
#col -b -x | kak -e "map global normal q ':quit!<ret>'; remove-highlighter window/number-lines_-relative_-separator_  "
