#!/bin/sh

# Only sync files with changes (buggy)
# rsync -uvrP --delete-after ~/capsules/uveronunix/ root@uveronunix.com:/srv/gemini/content

rsync -vrP --delete-after ~/capsules/uveronunix/ root@uveronunix.com:/srv/gemini/content
