#!/bin/sh
# ──────────────────────────────────
# ■           __  ___   _____  _____
# ■ ■        / / / / | / / _ \/ ___/
# ■ ■ ■     / /_/ /| |/ /  __/ /
# ■ ■ ■ ■   \____/ |___/\___/_/
# ──────────────────────────────────
  
# Autostart (handled by .xinitrc)
# ───────────────────────────────
# cursor-settings  # Cursor speed
# external-monitor # Turn off interal display if external is connected
# ~/.fehbg         # Set wallpaper
# picom &          # Run compositer

# sxhkd
# ─────
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor(s)
# ──────────
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# Gaps
# ────
bspc config top_padding         40
bspc config right_padding       40
bspc config bottom_padding      40
bspc config left_padding        40
bspc config window_gap           8
bspc config border_width         0

# Global
# ──────
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Behaviour
# ─────────
bspc config automatic_scheme alternate

# Mouse
# ─────
bspc config pointer_modifier        mod4
bspc config click_to_focus          none
bspc config focus_follows_pointer   true
xsetroot -cursor_name left_ptr &

# Rules
# ─────
bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
